export const GET_FRIEND_SUCCESS = "GET_FRIEND_SUCCESS";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const USER_SOCKET_MESSAGE = "USER_SOCKET_MESSAGE";
export const UPDATE_FRIEND_MESSAGE = "UPDATE_FRIEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS_CLEAR = "SEND_MESSAGE_SUCCESS_CLEAR";
